app:
  cors:
    debug: true
    allowedOrigin: "http://localhost:4200"

postgres:
  host: "localhost"
  port: 5432
  db: "timeline"
  user: "timeline"
  password: "timeline"
api:
  url: "http://localhost:7171/api"
