services:
  gowitness:
    image: ghcr.io/wert2all/gowitness:latest
    command: gowitness server --address 0.0.0.0:7171 --db-location=postgres://gowidness:gowidness12345@gowidnessdb/gowidness --debug-db
    depends_on:
      - gowidnessdb
    ports:
      - 7171:7171

  gowidnessdb:
    image: postgres:16.3
    environment:
      POSTGRES_USER: gowidness
      POSTGRES_PASSWORD: gowidness12345
      POSTGRES_DB: gowidness
    # ports:
    # - 5435:5432
  wswdb:
    image: postgres:16.3
    environment:
      POSTGRES_USER: wsw
      POSTGRES_PASSWORD: wsw12345
      POSTGRES_DB: wsw
    ports:
      - 5434:5432
