services:
  wswdb:
    image: postgres:16.3
    environment:
      POSTGRES_USER: wsw
      POSTGRES_PASSWORD: wsw
      POSTGRES_DB: wsw
    ports:
      - 5434:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile

    command: /app/previewly-backend -db-host wswdb
    ports:
      - 8000:8000
    depends_on:
      - wswdb
