services:
  gowitness:
    image: ghcr.io/sensepost/gowitness:latest
    command: gowitness report server --host 0.0.0.0 --port 7171 --screenshot-path /data/screenshots --db-uri postgres://gowidness:gowidness12345@gowidnessdb/gowidness
    volumes:
      - ./assets/screenshots:/data/screenshots
    depends_on:
      - gowidnessdb
    ports:
      - 7171:7171

  gowidnessdb:
    image: postgres:16.3
    environment:
      POSTGRES_USER: gowidness
      POSTGRES_PASSWORD: gowidness12345
      POSTGRES_DB: gowidness
    # ports:
    # - 5435:5432
  wswdb:
    image: postgres:16.3
    environment:
      POSTGRES_USER: wsw
      POSTGRES_PASSWORD: wsw
      POSTGRES_DB: wsw
    ports:
      - 5434:5432
