// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"wsw/backend/ent/errorresult"
	"wsw/backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ErrorResultQuery is the builder for querying ErrorResult entities.
type ErrorResultQuery struct {
	config
	ctx        *QueryContext
	order      []errorresult.OrderOption
	inters     []Interceptor
	predicates []predicate.ErrorResult
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ErrorResultQuery builder.
func (erq *ErrorResultQuery) Where(ps ...predicate.ErrorResult) *ErrorResultQuery {
	erq.predicates = append(erq.predicates, ps...)
	return erq
}

// Limit the number of records to be returned by this query.
func (erq *ErrorResultQuery) Limit(limit int) *ErrorResultQuery {
	erq.ctx.Limit = &limit
	return erq
}

// Offset to start from.
func (erq *ErrorResultQuery) Offset(offset int) *ErrorResultQuery {
	erq.ctx.Offset = &offset
	return erq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (erq *ErrorResultQuery) Unique(unique bool) *ErrorResultQuery {
	erq.ctx.Unique = &unique
	return erq
}

// Order specifies how the records should be ordered.
func (erq *ErrorResultQuery) Order(o ...errorresult.OrderOption) *ErrorResultQuery {
	erq.order = append(erq.order, o...)
	return erq
}

// First returns the first ErrorResult entity from the query.
// Returns a *NotFoundError when no ErrorResult was found.
func (erq *ErrorResultQuery) First(ctx context.Context) (*ErrorResult, error) {
	nodes, err := erq.Limit(1).All(setContextOp(ctx, erq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{errorresult.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (erq *ErrorResultQuery) FirstX(ctx context.Context) *ErrorResult {
	node, err := erq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ErrorResult ID from the query.
// Returns a *NotFoundError when no ErrorResult ID was found.
func (erq *ErrorResultQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = erq.Limit(1).IDs(setContextOp(ctx, erq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{errorresult.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (erq *ErrorResultQuery) FirstIDX(ctx context.Context) int {
	id, err := erq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ErrorResult entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ErrorResult entity is found.
// Returns a *NotFoundError when no ErrorResult entities are found.
func (erq *ErrorResultQuery) Only(ctx context.Context) (*ErrorResult, error) {
	nodes, err := erq.Limit(2).All(setContextOp(ctx, erq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{errorresult.Label}
	default:
		return nil, &NotSingularError{errorresult.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (erq *ErrorResultQuery) OnlyX(ctx context.Context) *ErrorResult {
	node, err := erq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ErrorResult ID in the query.
// Returns a *NotSingularError when more than one ErrorResult ID is found.
// Returns a *NotFoundError when no entities are found.
func (erq *ErrorResultQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = erq.Limit(2).IDs(setContextOp(ctx, erq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{errorresult.Label}
	default:
		err = &NotSingularError{errorresult.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (erq *ErrorResultQuery) OnlyIDX(ctx context.Context) int {
	id, err := erq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ErrorResults.
func (erq *ErrorResultQuery) All(ctx context.Context) ([]*ErrorResult, error) {
	ctx = setContextOp(ctx, erq.ctx, "All")
	if err := erq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ErrorResult, *ErrorResultQuery]()
	return withInterceptors[[]*ErrorResult](ctx, erq, qr, erq.inters)
}

// AllX is like All, but panics if an error occurs.
func (erq *ErrorResultQuery) AllX(ctx context.Context) []*ErrorResult {
	nodes, err := erq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ErrorResult IDs.
func (erq *ErrorResultQuery) IDs(ctx context.Context) (ids []int, err error) {
	if erq.ctx.Unique == nil && erq.path != nil {
		erq.Unique(true)
	}
	ctx = setContextOp(ctx, erq.ctx, "IDs")
	if err = erq.Select(errorresult.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (erq *ErrorResultQuery) IDsX(ctx context.Context) []int {
	ids, err := erq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (erq *ErrorResultQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, erq.ctx, "Count")
	if err := erq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, erq, querierCount[*ErrorResultQuery](), erq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (erq *ErrorResultQuery) CountX(ctx context.Context) int {
	count, err := erq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (erq *ErrorResultQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, erq.ctx, "Exist")
	switch _, err := erq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (erq *ErrorResultQuery) ExistX(ctx context.Context) bool {
	exist, err := erq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ErrorResultQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (erq *ErrorResultQuery) Clone() *ErrorResultQuery {
	if erq == nil {
		return nil
	}
	return &ErrorResultQuery{
		config:     erq.config,
		ctx:        erq.ctx.Clone(),
		order:      append([]errorresult.OrderOption{}, erq.order...),
		inters:     append([]Interceptor{}, erq.inters...),
		predicates: append([]predicate.ErrorResult{}, erq.predicates...),
		// clone intermediate query.
		sql:  erq.sql.Clone(),
		path: erq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ErrorResult.Query().
//		GroupBy(errorresult.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (erq *ErrorResultQuery) GroupBy(field string, fields ...string) *ErrorResultGroupBy {
	erq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ErrorResultGroupBy{build: erq}
	grbuild.flds = &erq.ctx.Fields
	grbuild.label = errorresult.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ErrorResult.Query().
//		Select(errorresult.FieldCreatedAt).
//		Scan(ctx, &v)
func (erq *ErrorResultQuery) Select(fields ...string) *ErrorResultSelect {
	erq.ctx.Fields = append(erq.ctx.Fields, fields...)
	sbuild := &ErrorResultSelect{ErrorResultQuery: erq}
	sbuild.label = errorresult.Label
	sbuild.flds, sbuild.scan = &erq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ErrorResultSelect configured with the given aggregations.
func (erq *ErrorResultQuery) Aggregate(fns ...AggregateFunc) *ErrorResultSelect {
	return erq.Select().Aggregate(fns...)
}

func (erq *ErrorResultQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range erq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, erq); err != nil {
				return err
			}
		}
	}
	for _, f := range erq.ctx.Fields {
		if !errorresult.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if erq.path != nil {
		prev, err := erq.path(ctx)
		if err != nil {
			return err
		}
		erq.sql = prev
	}
	return nil
}

func (erq *ErrorResultQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ErrorResult, error) {
	var (
		nodes   = []*ErrorResult{}
		withFKs = erq.withFKs
		_spec   = erq.querySpec()
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, errorresult.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ErrorResult).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ErrorResult{config: erq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, erq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (erq *ErrorResultQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := erq.querySpec()
	_spec.Node.Columns = erq.ctx.Fields
	if len(erq.ctx.Fields) > 0 {
		_spec.Unique = erq.ctx.Unique != nil && *erq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, erq.driver, _spec)
}

func (erq *ErrorResultQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(errorresult.Table, errorresult.Columns, sqlgraph.NewFieldSpec(errorresult.FieldID, field.TypeInt))
	_spec.From = erq.sql
	if unique := erq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if erq.path != nil {
		_spec.Unique = true
	}
	if fields := erq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, errorresult.FieldID)
		for i := range fields {
			if fields[i] != errorresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := erq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := erq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := erq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := erq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (erq *ErrorResultQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(erq.driver.Dialect())
	t1 := builder.Table(errorresult.Table)
	columns := erq.ctx.Fields
	if len(columns) == 0 {
		columns = errorresult.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if erq.sql != nil {
		selector = erq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if erq.ctx.Unique != nil && *erq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range erq.predicates {
		p(selector)
	}
	for _, p := range erq.order {
		p(selector)
	}
	if offset := erq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := erq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ErrorResultGroupBy is the group-by builder for ErrorResult entities.
type ErrorResultGroupBy struct {
	selector
	build *ErrorResultQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ergb *ErrorResultGroupBy) Aggregate(fns ...AggregateFunc) *ErrorResultGroupBy {
	ergb.fns = append(ergb.fns, fns...)
	return ergb
}

// Scan applies the selector query and scans the result into the given value.
func (ergb *ErrorResultGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ergb.build.ctx, "GroupBy")
	if err := ergb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ErrorResultQuery, *ErrorResultGroupBy](ctx, ergb.build, ergb, ergb.build.inters, v)
}

func (ergb *ErrorResultGroupBy) sqlScan(ctx context.Context, root *ErrorResultQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ergb.fns))
	for _, fn := range ergb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ergb.flds)+len(ergb.fns))
		for _, f := range *ergb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ergb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ergb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ErrorResultSelect is the builder for selecting fields of ErrorResult entities.
type ErrorResultSelect struct {
	*ErrorResultQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ers *ErrorResultSelect) Aggregate(fns ...AggregateFunc) *ErrorResultSelect {
	ers.fns = append(ers.fns, fns...)
	return ers
}

// Scan applies the selector query and scans the result into the given value.
func (ers *ErrorResultSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ers.ctx, "Select")
	if err := ers.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ErrorResultQuery, *ErrorResultSelect](ctx, ers.ErrorResultQuery, ers, ers.inters, v)
}

func (ers *ErrorResultSelect) sqlScan(ctx context.Context, root *ErrorResultQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ers.fns))
	for _, fn := range ers.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ers.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ers.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
