// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"wsw/backend/ent/errorresult"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ErrorResultCreate is the builder for creating a ErrorResult entity.
type ErrorResultCreate struct {
	config
	mutation *ErrorResultMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (erc *ErrorResultCreate) SetCreatedAt(t time.Time) *ErrorResultCreate {
	erc.mutation.SetCreatedAt(t)
	return erc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (erc *ErrorResultCreate) SetNillableCreatedAt(t *time.Time) *ErrorResultCreate {
	if t != nil {
		erc.SetCreatedAt(*t)
	}
	return erc
}

// SetMessage sets the "message" field.
func (erc *ErrorResultCreate) SetMessage(s string) *ErrorResultCreate {
	erc.mutation.SetMessage(s)
	return erc
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (erc *ErrorResultCreate) SetNillableMessage(s *string) *ErrorResultCreate {
	if s != nil {
		erc.SetMessage(*s)
	}
	return erc
}

// Mutation returns the ErrorResultMutation object of the builder.
func (erc *ErrorResultCreate) Mutation() *ErrorResultMutation {
	return erc.mutation
}

// Save creates the ErrorResult in the database.
func (erc *ErrorResultCreate) Save(ctx context.Context) (*ErrorResult, error) {
	erc.defaults()
	return withHooks(ctx, erc.sqlSave, erc.mutation, erc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (erc *ErrorResultCreate) SaveX(ctx context.Context) *ErrorResult {
	v, err := erc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (erc *ErrorResultCreate) Exec(ctx context.Context) error {
	_, err := erc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (erc *ErrorResultCreate) ExecX(ctx context.Context) {
	if err := erc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (erc *ErrorResultCreate) defaults() {
	if _, ok := erc.mutation.CreatedAt(); !ok {
		v := errorresult.DefaultCreatedAt()
		erc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (erc *ErrorResultCreate) check() error {
	if _, ok := erc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ErrorResult.created_at"`)}
	}
	return nil
}

func (erc *ErrorResultCreate) sqlSave(ctx context.Context) (*ErrorResult, error) {
	if err := erc.check(); err != nil {
		return nil, err
	}
	_node, _spec := erc.createSpec()
	if err := sqlgraph.CreateNode(ctx, erc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	erc.mutation.id = &_node.ID
	erc.mutation.done = true
	return _node, nil
}

func (erc *ErrorResultCreate) createSpec() (*ErrorResult, *sqlgraph.CreateSpec) {
	var (
		_node = &ErrorResult{config: erc.config}
		_spec = sqlgraph.NewCreateSpec(errorresult.Table, sqlgraph.NewFieldSpec(errorresult.FieldID, field.TypeInt))
	)
	if value, ok := erc.mutation.CreatedAt(); ok {
		_spec.SetField(errorresult.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := erc.mutation.Message(); ok {
		_spec.SetField(errorresult.FieldMessage, field.TypeString, value)
		_node.Message = &value
	}
	return _node, _spec
}

// ErrorResultCreateBulk is the builder for creating many ErrorResult entities in bulk.
type ErrorResultCreateBulk struct {
	config
	err      error
	builders []*ErrorResultCreate
}

// Save creates the ErrorResult entities in the database.
func (ercb *ErrorResultCreateBulk) Save(ctx context.Context) ([]*ErrorResult, error) {
	if ercb.err != nil {
		return nil, ercb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ercb.builders))
	nodes := make([]*ErrorResult, len(ercb.builders))
	mutators := make([]Mutator, len(ercb.builders))
	for i := range ercb.builders {
		func(i int, root context.Context) {
			builder := ercb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ErrorResultMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ercb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ercb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ercb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ercb *ErrorResultCreateBulk) SaveX(ctx context.Context) []*ErrorResult {
	v, err := ercb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ercb *ErrorResultCreateBulk) Exec(ctx context.Context) error {
	_, err := ercb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ercb *ErrorResultCreateBulk) ExecX(ctx context.Context) {
	if err := ercb.Exec(ctx); err != nil {
		panic(err)
	}
}
