// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"wsw/backend/ent/image"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Image is the model entity for the Image schema.
type Image struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Filename holds the value of the "filename" field.
	Filename string `json:"filename,omitempty"`
	// DestinationPath holds the value of the "destination_path" field.
	DestinationPath string `json:"destination_path,omitempty"`
	// OriginalFilename holds the value of the "original_filename" field.
	OriginalFilename string `json:"original_filename,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// ExtraValue holds the value of the "extra_value" field.
	ExtraValue *string `json:"extra_value,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ImageQuery when eager-loading is set.
	Edges        ImageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ImageEdges holds the relations/edges for other nodes in the graph.
type ImageEdges struct {
	// Imageprocess holds the value of the imageprocess edge.
	Imageprocess []*ImageProcess `json:"imageprocess,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ImageprocessOrErr returns the Imageprocess value or an error if the edge
// was not loaded in eager-loading.
func (e ImageEdges) ImageprocessOrErr() ([]*ImageProcess, error) {
	if e.loadedTypes[0] {
		return e.Imageprocess, nil
	}
	return nil, &NotLoadedError{edge: "imageprocess"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Image) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case image.FieldID:
			values[i] = new(sql.NullInt64)
		case image.FieldFilename, image.FieldDestinationPath, image.FieldOriginalFilename, image.FieldType, image.FieldExtraValue:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Image fields.
func (i *Image) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for j := range columns {
		switch columns[j] {
		case image.FieldID:
			value, ok := values[j].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			i.ID = int(value.Int64)
		case image.FieldFilename:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field filename", values[j])
			} else if value.Valid {
				i.Filename = value.String
			}
		case image.FieldDestinationPath:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field destination_path", values[j])
			} else if value.Valid {
				i.DestinationPath = value.String
			}
		case image.FieldOriginalFilename:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_filename", values[j])
			} else if value.Valid {
				i.OriginalFilename = value.String
			}
		case image.FieldType:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[j])
			} else if value.Valid {
				i.Type = value.String
			}
		case image.FieldExtraValue:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field extra_value", values[j])
			} else if value.Valid {
				i.ExtraValue = new(string)
				*i.ExtraValue = value.String
			}
		default:
			i.selectValues.Set(columns[j], values[j])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Image.
// This includes values selected through modifiers, order, etc.
func (i *Image) Value(name string) (ent.Value, error) {
	return i.selectValues.Get(name)
}

// QueryImageprocess queries the "imageprocess" edge of the Image entity.
func (i *Image) QueryImageprocess() *ImageProcessQuery {
	return NewImageClient(i.config).QueryImageprocess(i)
}

// Update returns a builder for updating this Image.
// Note that you need to call Image.Unwrap() before calling this method if this Image
// was returned from a transaction, and the transaction was committed or rolled back.
func (i *Image) Update() *ImageUpdateOne {
	return NewImageClient(i.config).UpdateOne(i)
}

// Unwrap unwraps the Image entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (i *Image) Unwrap() *Image {
	_tx, ok := i.config.driver.(*txDriver)
	if !ok {
		panic("ent: Image is not a transactional entity")
	}
	i.config.driver = _tx.drv
	return i
}

// String implements the fmt.Stringer.
func (i *Image) String() string {
	var builder strings.Builder
	builder.WriteString("Image(")
	builder.WriteString(fmt.Sprintf("id=%v, ", i.ID))
	builder.WriteString("filename=")
	builder.WriteString(i.Filename)
	builder.WriteString(", ")
	builder.WriteString("destination_path=")
	builder.WriteString(i.DestinationPath)
	builder.WriteString(", ")
	builder.WriteString("original_filename=")
	builder.WriteString(i.OriginalFilename)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(i.Type)
	builder.WriteString(", ")
	if v := i.ExtraValue; v != nil {
		builder.WriteString("extra_value=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// Images is a parsable slice of Image.
type Images []*Image
