// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
	"wsw/backend/ent/image"
	"wsw/backend/ent/imageprocess"
	"wsw/backend/ent/types"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ImageProcess is the model entity for the ImageProcess schema.
type ImageProcess struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status types.StatusEnum `json:"status,omitempty"`
	// ProcessHash holds the value of the "process_hash" field.
	ProcessHash string `json:"process_hash,omitempty"`
	// Processes holds the value of the "processes" field.
	Processes []types.ImageProcess `json:"processes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PathPrefix holds the value of the "path_prefix" field.
	PathPrefix string `json:"path_prefix,omitempty"`
	// Error holds the value of the "error" field.
	Error string `json:"error,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ImageProcessQuery when eager-loading is set.
	Edges              ImageProcessEdges `json:"edges"`
	image_imageprocess *int
	selectValues       sql.SelectValues
}

// ImageProcessEdges holds the relations/edges for other nodes in the graph.
type ImageProcessEdges struct {
	// Uploadimage holds the value of the uploadimage edge.
	Uploadimage *Image `json:"uploadimage,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UploadimageOrErr returns the Uploadimage value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ImageProcessEdges) UploadimageOrErr() (*Image, error) {
	if e.Uploadimage != nil {
		return e.Uploadimage, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: image.Label}
	}
	return nil, &NotLoadedError{edge: "uploadimage"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImageProcess) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imageprocess.FieldProcesses:
			values[i] = new([]byte)
		case imageprocess.FieldID:
			values[i] = new(sql.NullInt64)
		case imageprocess.FieldStatus, imageprocess.FieldProcessHash, imageprocess.FieldPathPrefix, imageprocess.FieldError:
			values[i] = new(sql.NullString)
		case imageprocess.FieldCreatedAt, imageprocess.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case imageprocess.ForeignKeys[0]: // image_imageprocess
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImageProcess fields.
func (ip *ImageProcess) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imageprocess.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ip.ID = int(value.Int64)
		case imageprocess.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ip.Status = types.StatusEnum(value.String)
			}
		case imageprocess.FieldProcessHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field process_hash", values[i])
			} else if value.Valid {
				ip.ProcessHash = value.String
			}
		case imageprocess.FieldProcesses:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field processes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ip.Processes); err != nil {
					return fmt.Errorf("unmarshal field processes: %w", err)
				}
			}
		case imageprocess.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ip.CreatedAt = value.Time
			}
		case imageprocess.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ip.UpdatedAt = value.Time
			}
		case imageprocess.FieldPathPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path_prefix", values[i])
			} else if value.Valid {
				ip.PathPrefix = value.String
			}
		case imageprocess.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				ip.Error = value.String
			}
		case imageprocess.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field image_imageprocess", value)
			} else if value.Valid {
				ip.image_imageprocess = new(int)
				*ip.image_imageprocess = int(value.Int64)
			}
		default:
			ip.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImageProcess.
// This includes values selected through modifiers, order, etc.
func (ip *ImageProcess) Value(name string) (ent.Value, error) {
	return ip.selectValues.Get(name)
}

// QueryUploadimage queries the "uploadimage" edge of the ImageProcess entity.
func (ip *ImageProcess) QueryUploadimage() *ImageQuery {
	return NewImageProcessClient(ip.config).QueryUploadimage(ip)
}

// Update returns a builder for updating this ImageProcess.
// Note that you need to call ImageProcess.Unwrap() before calling this method if this ImageProcess
// was returned from a transaction, and the transaction was committed or rolled back.
func (ip *ImageProcess) Update() *ImageProcessUpdateOne {
	return NewImageProcessClient(ip.config).UpdateOne(ip)
}

// Unwrap unwraps the ImageProcess entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ip *ImageProcess) Unwrap() *ImageProcess {
	_tx, ok := ip.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImageProcess is not a transactional entity")
	}
	ip.config.driver = _tx.drv
	return ip
}

// String implements the fmt.Stringer.
func (ip *ImageProcess) String() string {
	var builder strings.Builder
	builder.WriteString("ImageProcess(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ip.ID))
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", ip.Status))
	builder.WriteString(", ")
	builder.WriteString("process_hash=")
	builder.WriteString(ip.ProcessHash)
	builder.WriteString(", ")
	builder.WriteString("processes=")
	builder.WriteString(fmt.Sprintf("%v", ip.Processes))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ip.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ip.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("path_prefix=")
	builder.WriteString(ip.PathPrefix)
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(ip.Error)
	builder.WriteByte(')')
	return builder.String()
}

// ImageProcesses is a parsable slice of ImageProcess.
type ImageProcesses []*ImageProcess
