// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"wsw/backend/ent/stat"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Stat is the model entity for the Stat schema.
type Stat struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Title holds the value of the "title" field.
	Title        *string `json:"title,omitempty"`
	url_stat     *int
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Stat) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case stat.FieldID:
			values[i] = new(sql.NullInt64)
		case stat.FieldTitle:
			values[i] = new(sql.NullString)
		case stat.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case stat.ForeignKeys[0]: // url_stat
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Stat fields.
func (s *Stat) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stat.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case stat.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				s.CreatedAt = value.Time
			}
		case stat.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				s.Title = new(string)
				*s.Title = value.String
			}
		case stat.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field url_stat", value)
			} else if value.Valid {
				s.url_stat = new(int)
				*s.url_stat = int(value.Int64)
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Stat.
// This includes values selected through modifiers, order, etc.
func (s *Stat) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// Update returns a builder for updating this Stat.
// Note that you need to call Stat.Unwrap() before calling this method if this Stat
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Stat) Update() *StatUpdateOne {
	return NewStatClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Stat entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Stat) Unwrap() *Stat {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Stat is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Stat) String() string {
	var builder strings.Builder
	builder.WriteString("Stat(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("created_at=")
	builder.WriteString(s.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := s.Title; v != nil {
		builder.WriteString("title=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// Stats is a parsable slice of Stat.
type Stats []*Stat
