// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"wsw/backend/ent/imageprocess"
	"wsw/backend/ent/predicate"
	"wsw/backend/ent/uploadimage"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UploadImageQuery is the builder for querying UploadImage entities.
type UploadImageQuery struct {
	config
	ctx              *QueryContext
	order            []uploadimage.OrderOption
	inters           []Interceptor
	predicates       []predicate.UploadImage
	withImageprocess *ImageProcessQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UploadImageQuery builder.
func (uiq *UploadImageQuery) Where(ps ...predicate.UploadImage) *UploadImageQuery {
	uiq.predicates = append(uiq.predicates, ps...)
	return uiq
}

// Limit the number of records to be returned by this query.
func (uiq *UploadImageQuery) Limit(limit int) *UploadImageQuery {
	uiq.ctx.Limit = &limit
	return uiq
}

// Offset to start from.
func (uiq *UploadImageQuery) Offset(offset int) *UploadImageQuery {
	uiq.ctx.Offset = &offset
	return uiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uiq *UploadImageQuery) Unique(unique bool) *UploadImageQuery {
	uiq.ctx.Unique = &unique
	return uiq
}

// Order specifies how the records should be ordered.
func (uiq *UploadImageQuery) Order(o ...uploadimage.OrderOption) *UploadImageQuery {
	uiq.order = append(uiq.order, o...)
	return uiq
}

// QueryImageprocess chains the current query on the "imageprocess" edge.
func (uiq *UploadImageQuery) QueryImageprocess() *ImageProcessQuery {
	query := (&ImageProcessClient{config: uiq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uiq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(uploadimage.Table, uploadimage.FieldID, selector),
			sqlgraph.To(imageprocess.Table, imageprocess.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, uploadimage.ImageprocessTable, uploadimage.ImageprocessColumn),
		)
		fromU = sqlgraph.SetNeighbors(uiq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UploadImage entity from the query.
// Returns a *NotFoundError when no UploadImage was found.
func (uiq *UploadImageQuery) First(ctx context.Context) (*UploadImage, error) {
	nodes, err := uiq.Limit(1).All(setContextOp(ctx, uiq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{uploadimage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uiq *UploadImageQuery) FirstX(ctx context.Context) *UploadImage {
	node, err := uiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UploadImage ID from the query.
// Returns a *NotFoundError when no UploadImage ID was found.
func (uiq *UploadImageQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uiq.Limit(1).IDs(setContextOp(ctx, uiq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{uploadimage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uiq *UploadImageQuery) FirstIDX(ctx context.Context) int {
	id, err := uiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UploadImage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UploadImage entity is found.
// Returns a *NotFoundError when no UploadImage entities are found.
func (uiq *UploadImageQuery) Only(ctx context.Context) (*UploadImage, error) {
	nodes, err := uiq.Limit(2).All(setContextOp(ctx, uiq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{uploadimage.Label}
	default:
		return nil, &NotSingularError{uploadimage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uiq *UploadImageQuery) OnlyX(ctx context.Context) *UploadImage {
	node, err := uiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UploadImage ID in the query.
// Returns a *NotSingularError when more than one UploadImage ID is found.
// Returns a *NotFoundError when no entities are found.
func (uiq *UploadImageQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uiq.Limit(2).IDs(setContextOp(ctx, uiq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{uploadimage.Label}
	default:
		err = &NotSingularError{uploadimage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uiq *UploadImageQuery) OnlyIDX(ctx context.Context) int {
	id, err := uiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UploadImages.
func (uiq *UploadImageQuery) All(ctx context.Context) ([]*UploadImage, error) {
	ctx = setContextOp(ctx, uiq.ctx, ent.OpQueryAll)
	if err := uiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UploadImage, *UploadImageQuery]()
	return withInterceptors[[]*UploadImage](ctx, uiq, qr, uiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uiq *UploadImageQuery) AllX(ctx context.Context) []*UploadImage {
	nodes, err := uiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UploadImage IDs.
func (uiq *UploadImageQuery) IDs(ctx context.Context) (ids []int, err error) {
	if uiq.ctx.Unique == nil && uiq.path != nil {
		uiq.Unique(true)
	}
	ctx = setContextOp(ctx, uiq.ctx, ent.OpQueryIDs)
	if err = uiq.Select(uploadimage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uiq *UploadImageQuery) IDsX(ctx context.Context) []int {
	ids, err := uiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uiq *UploadImageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uiq.ctx, ent.OpQueryCount)
	if err := uiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uiq, querierCount[*UploadImageQuery](), uiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uiq *UploadImageQuery) CountX(ctx context.Context) int {
	count, err := uiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uiq *UploadImageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uiq.ctx, ent.OpQueryExist)
	switch _, err := uiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uiq *UploadImageQuery) ExistX(ctx context.Context) bool {
	exist, err := uiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UploadImageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uiq *UploadImageQuery) Clone() *UploadImageQuery {
	if uiq == nil {
		return nil
	}
	return &UploadImageQuery{
		config:           uiq.config,
		ctx:              uiq.ctx.Clone(),
		order:            append([]uploadimage.OrderOption{}, uiq.order...),
		inters:           append([]Interceptor{}, uiq.inters...),
		predicates:       append([]predicate.UploadImage{}, uiq.predicates...),
		withImageprocess: uiq.withImageprocess.Clone(),
		// clone intermediate query.
		sql:  uiq.sql.Clone(),
		path: uiq.path,
	}
}

// WithImageprocess tells the query-builder to eager-load the nodes that are connected to
// the "imageprocess" edge. The optional arguments are used to configure the query builder of the edge.
func (uiq *UploadImageQuery) WithImageprocess(opts ...func(*ImageProcessQuery)) *UploadImageQuery {
	query := (&ImageProcessClient{config: uiq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	uiq.withImageprocess = query
	return uiq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Filename string `json:"filename,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UploadImage.Query().
//		GroupBy(uploadimage.FieldFilename).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uiq *UploadImageQuery) GroupBy(field string, fields ...string) *UploadImageGroupBy {
	uiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UploadImageGroupBy{build: uiq}
	grbuild.flds = &uiq.ctx.Fields
	grbuild.label = uploadimage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Filename string `json:"filename,omitempty"`
//	}
//
//	client.UploadImage.Query().
//		Select(uploadimage.FieldFilename).
//		Scan(ctx, &v)
func (uiq *UploadImageQuery) Select(fields ...string) *UploadImageSelect {
	uiq.ctx.Fields = append(uiq.ctx.Fields, fields...)
	sbuild := &UploadImageSelect{UploadImageQuery: uiq}
	sbuild.label = uploadimage.Label
	sbuild.flds, sbuild.scan = &uiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UploadImageSelect configured with the given aggregations.
func (uiq *UploadImageQuery) Aggregate(fns ...AggregateFunc) *UploadImageSelect {
	return uiq.Select().Aggregate(fns...)
}

func (uiq *UploadImageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uiq); err != nil {
				return err
			}
		}
	}
	for _, f := range uiq.ctx.Fields {
		if !uploadimage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uiq.path != nil {
		prev, err := uiq.path(ctx)
		if err != nil {
			return err
		}
		uiq.sql = prev
	}
	return nil
}

func (uiq *UploadImageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UploadImage, error) {
	var (
		nodes       = []*UploadImage{}
		_spec       = uiq.querySpec()
		loadedTypes = [1]bool{
			uiq.withImageprocess != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UploadImage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UploadImage{config: uiq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := uiq.withImageprocess; query != nil {
		if err := uiq.loadImageprocess(ctx, query, nodes,
			func(n *UploadImage) { n.Edges.Imageprocess = []*ImageProcess{} },
			func(n *UploadImage, e *ImageProcess) { n.Edges.Imageprocess = append(n.Edges.Imageprocess, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (uiq *UploadImageQuery) loadImageprocess(ctx context.Context, query *ImageProcessQuery, nodes []*UploadImage, init func(*UploadImage), assign func(*UploadImage, *ImageProcess)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*UploadImage)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ImageProcess(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(uploadimage.ImageprocessColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.upload_image_imageprocess
		if fk == nil {
			return fmt.Errorf(`foreign-key "upload_image_imageprocess" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "upload_image_imageprocess" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (uiq *UploadImageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uiq.querySpec()
	_spec.Node.Columns = uiq.ctx.Fields
	if len(uiq.ctx.Fields) > 0 {
		_spec.Unique = uiq.ctx.Unique != nil && *uiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uiq.driver, _spec)
}

func (uiq *UploadImageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(uploadimage.Table, uploadimage.Columns, sqlgraph.NewFieldSpec(uploadimage.FieldID, field.TypeInt))
	_spec.From = uiq.sql
	if unique := uiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uiq.path != nil {
		_spec.Unique = true
	}
	if fields := uiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, uploadimage.FieldID)
		for i := range fields {
			if fields[i] != uploadimage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uiq *UploadImageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uiq.driver.Dialect())
	t1 := builder.Table(uploadimage.Table)
	columns := uiq.ctx.Fields
	if len(columns) == 0 {
		columns = uploadimage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uiq.sql != nil {
		selector = uiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uiq.ctx.Unique != nil && *uiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uiq.predicates {
		p(selector)
	}
	for _, p := range uiq.order {
		p(selector)
	}
	if offset := uiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UploadImageGroupBy is the group-by builder for UploadImage entities.
type UploadImageGroupBy struct {
	selector
	build *UploadImageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uigb *UploadImageGroupBy) Aggregate(fns ...AggregateFunc) *UploadImageGroupBy {
	uigb.fns = append(uigb.fns, fns...)
	return uigb
}

// Scan applies the selector query and scans the result into the given value.
func (uigb *UploadImageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uigb.build.ctx, ent.OpQueryGroupBy)
	if err := uigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UploadImageQuery, *UploadImageGroupBy](ctx, uigb.build, uigb, uigb.build.inters, v)
}

func (uigb *UploadImageGroupBy) sqlScan(ctx context.Context, root *UploadImageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uigb.fns))
	for _, fn := range uigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uigb.flds)+len(uigb.fns))
		for _, f := range *uigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UploadImageSelect is the builder for selecting fields of UploadImage entities.
type UploadImageSelect struct {
	*UploadImageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uis *UploadImageSelect) Aggregate(fns ...AggregateFunc) *UploadImageSelect {
	uis.fns = append(uis.fns, fns...)
	return uis
}

// Scan applies the selector query and scans the result into the given value.
func (uis *UploadImageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uis.ctx, ent.OpQuerySelect)
	if err := uis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UploadImageQuery, *UploadImageSelect](ctx, uis.UploadImageQuery, uis, uis.inters, v)
}

func (uis *UploadImageSelect) sqlScan(ctx context.Context, root *UploadImageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uis.fns))
	for _, fn := range uis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
