// Code generated by ent, DO NOT EDIT.

package imageprocess

import (
	"time"
	"wsw/backend/ent/predicate"
	"wsw/backend/ent/types"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldEQ(FieldUpdatedAt, v))
}

// PathPrefix applies equality check predicate on the "path_prefix" field. It's identical to PathPrefixEQ.
func PathPrefix(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldEQ(FieldPathPrefix, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldEQ(FieldError, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v types.StatusEnum) predicate.ImageProcess {
	vc := v
	return predicate.ImageProcess(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v types.StatusEnum) predicate.ImageProcess {
	vc := v
	return predicate.ImageProcess(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...types.StatusEnum) predicate.ImageProcess {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ImageProcess(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...types.StatusEnum) predicate.ImageProcess {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ImageProcess(sql.FieldNotIn(FieldStatus, v...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldLTE(FieldUpdatedAt, v))
}

// PathPrefixEQ applies the EQ predicate on the "path_prefix" field.
func PathPrefixEQ(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldEQ(FieldPathPrefix, v))
}

// PathPrefixNEQ applies the NEQ predicate on the "path_prefix" field.
func PathPrefixNEQ(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldNEQ(FieldPathPrefix, v))
}

// PathPrefixIn applies the In predicate on the "path_prefix" field.
func PathPrefixIn(vs ...string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldIn(FieldPathPrefix, vs...))
}

// PathPrefixNotIn applies the NotIn predicate on the "path_prefix" field.
func PathPrefixNotIn(vs ...string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldNotIn(FieldPathPrefix, vs...))
}

// PathPrefixGT applies the GT predicate on the "path_prefix" field.
func PathPrefixGT(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldGT(FieldPathPrefix, v))
}

// PathPrefixGTE applies the GTE predicate on the "path_prefix" field.
func PathPrefixGTE(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldGTE(FieldPathPrefix, v))
}

// PathPrefixLT applies the LT predicate on the "path_prefix" field.
func PathPrefixLT(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldLT(FieldPathPrefix, v))
}

// PathPrefixLTE applies the LTE predicate on the "path_prefix" field.
func PathPrefixLTE(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldLTE(FieldPathPrefix, v))
}

// PathPrefixContains applies the Contains predicate on the "path_prefix" field.
func PathPrefixContains(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldContains(FieldPathPrefix, v))
}

// PathPrefixHasPrefix applies the HasPrefix predicate on the "path_prefix" field.
func PathPrefixHasPrefix(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldHasPrefix(FieldPathPrefix, v))
}

// PathPrefixHasSuffix applies the HasSuffix predicate on the "path_prefix" field.
func PathPrefixHasSuffix(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldHasSuffix(FieldPathPrefix, v))
}

// PathPrefixIsNil applies the IsNil predicate on the "path_prefix" field.
func PathPrefixIsNil() predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldIsNull(FieldPathPrefix))
}

// PathPrefixNotNil applies the NotNil predicate on the "path_prefix" field.
func PathPrefixNotNil() predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldNotNull(FieldPathPrefix))
}

// PathPrefixEqualFold applies the EqualFold predicate on the "path_prefix" field.
func PathPrefixEqualFold(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldEqualFold(FieldPathPrefix, v))
}

// PathPrefixContainsFold applies the ContainsFold predicate on the "path_prefix" field.
func PathPrefixContainsFold(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldContainsFold(FieldPathPrefix, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.ImageProcess {
	return predicate.ImageProcess(sql.FieldContainsFold(FieldError, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ImageProcess) predicate.ImageProcess {
	return predicate.ImageProcess(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ImageProcess) predicate.ImageProcess {
	return predicate.ImageProcess(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ImageProcess) predicate.ImageProcess {
	return predicate.ImageProcess(sql.NotPredicates(p))
}
