// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ErrorResult is the predicate function for errorresult builders.
type ErrorResult func(*sql.Selector)

// Stat is the predicate function for stat builders.
type Stat func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// UploadImage is the predicate function for uploadimage builders.
type UploadImage func(*sql.Selector)

// Url is the predicate function for url builders.
type Url func(*sql.Selector)
